### ISSUE TITLE
Background Image isn't being displayed

### ISSUE THREAD

**Issue by abhishek-gaonkar** [matthewlucock/pure-atom#1]
## Expected Behavior
Background Image is supposed to appear 

## Actual Behavior
A solid black background is being displayed

## Steps to Reproduce the Problem

  1. Set UI theme to Pure.
  2. Set Syntax theme to everything available but still there is no visible change.
  3. Tried changing alpha (both) to different values.
Only solid colors work. Do check. Thanks

## Specifications

  - Version: pure-ui 1.0.2; Atom 1.32.1
  - Platform: Windows

**Comment by matthewlucock** [comment]
I'm afraid this doesn't replicate for me on Windows, but there a few things that I can think of that could be causing this.

If you open the dev tools (Ctrl + Shift + I) and select the `<body>` element, does it have a `background-image` style applied to it? Something like
![image](https://user-images.githubusercontent.com/2455682/47964970-ee253e80-e094-11e8-935b-cbcf678e83c8.png)

If so, what is the url of the image? While you're in the dev tools, any errors that are in the console would be of use to me.

Also, does the image selection view function as expected, even if the images themselves don't? (The thumbnails load, you can select images, you can add and select custom images)

**Comment by abhishek-gaonkar** [comment]
Hey man,
Sorry I checked late. There is no background-image element itself. That's why there is simply solid black background-color. Attaching an image.
(https://user-images.githubusercontent.com/31586736/49341243-a7653d00-f670-11e8-8d20-b3511b88eeda.JPG)

I tried inserting background-image element in styles but even temporarily it's not working like that.
